// Compiled by ClojureScript 1.10.520 {:static-fns true, :optimize-constants true}
goog.provide('material_ui.core');
goog.require('cljs.core');
goog.require('cljs.core.constants');
goog.require('reagent.core');
material_ui.core.global$module$material_ui_styles = goog.global["MaterialUiStyles"];
material_ui.core.global$module$material_ui_core = goog.global["MaterialUiCore"];
material_ui.core.create_mui_theme = material_ui.core.global$module$material_ui_styles.createMuiTheme;
material_ui.core.mui_theme_provider = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_styles.MuiThemeProvider);
material_ui.core.grid = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.Grid);
material_ui.core.app_bar = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.AppBar);
material_ui.core.button = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.Button);
material_ui.core.checkbox = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.Checkbox);
material_ui.core.chip = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.Chip);
material_ui.core.input = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.Input);
material_ui.core.input_label = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.InputLabel);
material_ui.core.form_control_label = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.FormControlLabel);
material_ui.core.form_control = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.FormControl);
material_ui.core.form_helper_text = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.FormHelperText);
material_ui.core.native_select = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.NativeSelect);
material_ui.core.radio = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.Radio);
material_ui.core.radio_group = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.RadioGroup);
material_ui.core.select = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.Select);
material_ui.core.tab = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.Tab);
material_ui.core.tabs = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.Tabs);
material_ui.core.toolbar = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.Toolbar);
material_ui.core.typography = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.Typography);
material_ui.core.text_field = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.TextField);
material_ui.core.menu_item = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.MenuItem);
material_ui.core.paper = reagent.core.adapt_react_class(material_ui.core.global$module$material_ui_core.Paper);
