name: master tests

on:
  push:
    branches:
    - master

jobs:
  tests:
    runs-on: ubuntu-18.04
    steps:
    - name: checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Install java
      uses: actions/setup-java@v1
      with:
        java-version: '13.0.1'

    - name: Install clojure
      uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: '1.10.1.478'

    - name: Tests
      run: clojure -A:test:test-once

    - name: Slack notifications
      uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        author_name: GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()